### ISSUE TITLE
DataMatrix

### ISSUE THREAD

**Issue by zhendosina** [Merricx/qrazybox#1]
Hi! Thank you, great tool! Any plans about datamatrix code? :))

**Comment by Merricx** [comment]
Hi, glad to hear that :D
Data matrix code structure is different compared with QR code (although it use same error correction method) and maybe need to rework all the code to achieve that
Therefore I will only focusing this tool on QR code

**Comment by zhendosina** [comment]
it's sad, but where can I read about partial code recovery? I really liked the feature and really need it for Datamatrix
Thank you!
