### ISSUE TITLE
Tool support for ECI mode

### ISSUE THREAD

**Issue by bb010g** [Merricx/qrazybox#3]
Currently, tools like "Extract QR Information" fail on codes using ECI modes with "Invalid Encoding mode". Tested with a code beginning with mode: 7, ECI indicator: 26, mode: 4, length: …, ….

**Comment by Merricx** [comment]
Support for ECI Mode added: https://github.com/Merricx/qrazybox/commit/12df65b9d60da1c00892d2d3d871a08f6c6be8ca
